version: "3"
services: 
    redis-node-1:
        image: redis
        container_name: "redis-node-1"
        networks: 
          redis-cluster:
            ipv4_address: 172.0.0.2
            
        working_dir: /usr/local/redis
        volumes: 
          - ./node-1/data:/usr/local/redis/data
          - ./node-1/conf/redis.conf:/usr/local/redis/conf/redis.conf
        command: /usr/local/redis/conf/redis.conf
    redis-node-2:
        image: redis
        container_name: "redis-node-2"
        networks: 
          redis-cluster:
            ipv4_address: 172.0.0.3
        working_dir: /usr/local/redis
        volumes: 
          - ./node-2/data:/usr/local/redis/data
          - ./node-2/conf/redis.conf:/usr/local/redis/conf/redis.conf
        command: /usr/local/redis/conf/redis.conf
    redis-node-3:
        image: redis
        container_name: "redis-node-3"
        networks: 
          redis-cluster:
            ipv4_address: 172.0.0.4
        working_dir: /usr/local/redis
        volumes: 
          - ./node-3/data:/usr/local/redis/data
          - ./node-3/conf/redis.conf:/usr/local/redis/conf/redis.conf
        command: /usr/local/redis/conf/redis.conf
    redis-node-4:
        image: redis
        container_name: "redis-node-4"
        networks: 
          redis-cluster:
            ipv4_address: 172.0.0.5
        working_dir: /usr/local/redis
        volumes: 
          - ./node-4/data:/usr/local/redis/data
          - ./node-4/conf/redis.conf:/usr/local/redis/conf/redis.conf
        command: /usr/local/redis/conf/redis.conf
    redis-node-5:
        image: redis
        container_name: "redis-node-5"
        networks: 
          redis-cluster:
            ipv4_address: 172.0.0.6
        working_dir: /usr/local/redis
        volumes: 
          - ./node-5/data:/usr/local/redis/data
          - ./node-5/conf/redis.conf:/usr/local/redis/conf/redis.conf
        command: /usr/local/redis/conf/redis.conf
    redis-node-6:
        image: redis
        container_name: "redis-node-6"
        networks: 
          redis-cluster:
            ipv4_address: 172.0.0.7
        working_dir: /usr/local/redis
        volumes: 
          - ./node-6/data:/usr/local/redis/data
          - ./node-6/conf/redis.conf:/usr/local/redis/conf/redis.conf
        command: /usr/local/redis/conf/redis.conf              

networks:
  redis-cluster:
    ipam: 
      config: 
        - subnet: 172.0.0.0/28

