version: "3"
services: 
    es7:
        container_name: "es7"
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        environment: 
            discovery.type: "single-node"
            ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
        ports: 
            - 9200:9200
            - 9300:9300
        networks: 
            icepan:
                ipv4_address: 192.168.0.2
        volumes: 
            - ./plugins:/usr/share/elasticsearch/plugins
            - ./data:/usr/share/elasticsearch/data
    kibana:
        container_name: "kibana"
        image: docker.elastic.co/kibana/kibana:7.8.1
        environment: 
            ELASTICSEARCH_HOSTS: "http://es7:9200"
        ports: 
            - 5601:5601
        networks: 
            icepan:
                ipv4_address: 192.168.0.3
        depends_on: 
            - es7
        


networks: 
    icepan:
        external: 
            name: icepan
        
