version: '3'
services:
  nginx1:
    container_name: n1
    image: nginx
    networks:
      icepan:
        ipv4_address: 192.168.0.2
  nginx2:
    container_name: n2
    image: nginx
    networks:
      icepan:
        ipv4_address: 192.168.0.3
networks:
  icepan:
    external:
      name: icepan
